[versions]
activityCompose = "1.8.2"
core = "1.12.0"
coreKtx = "1.12.0"
lifeCycleRuntime = "2.6.2"
composeActivity = "1.8.1"
composeBom = "2023.08.00"
junit = "4.13.2"
androidJunit = "1.1.5"
espresso = "3.5.1"
appCompat = "1.6.1"
materialVersion = "1.2.0-beta01"
lifecycleRuntimeKtx = "2.6.2"
retrofit = "2.9.0"
okHttp = "4.1.0"
hilt = "2.48"
navVersion = "2.7.6"
coil = "2.5.0"
viewModelLifeCycle = "1.0.0-alpha03"
hiltCompiler = "1.0.0-alpha03"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

#deps
core = { module = "androidx.core:core-ktx", version.ref = "core" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "materialVersion"}


#[coroutinesLifeCycleScope]
lifeCycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifeCycleRuntime" }

#[jetPackCompose]
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeGraphics = { module = "androidx.compose.ui:ui-graphics" }
composePreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeMaterial = { module = "androidx.compose.material3:material3" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }


#[testImplementation]
junit = {  module = "junit:junit", version.ref ="junit" }

#[androidTestImplementation]
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidJunit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
composeUiTest = { module = "androidx.compose.ui:ui-test-junit4" }

#[debugImplementation]
toolingUi = { module = "androidx.compose.ui:ui-tooling"}
manifestTest =  { module ="androidx.compose.ui:ui-test-manifest"}

#[retrofit]
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }

#[coil]
coilImplementation = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

#[daggerHilt]
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
viewModelLifeCycle = { module = "androidx.hilt:hilt-lifecycle-viewmodel" , version.ref = "viewModelLifeCycle" }
viewModelCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hiltCompose = { module = "androidx.hilt:hilt-navigation-compose" , version.ref = "hiltCompiler" }
